biblio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from shelf.views import MainPageView
from contact.views import MessageAddView



urlpatterns = [



    url(r'^admin/', admin.site.urls),
    url(r'^shelf/',include('shelf.urls', namespace='shelf')),
    url(r'^contact/$',MessageAddView.as_view()),
    url(r'^$',MainPageView.as_view(),name='main-page'),
    #url(r'^$', 'shelf.views.index_view',name='main-page'),



    url(r'^accounts/', include('allauth.urls')),

        ]

shelf/urls.py
from django.conf.urls import url, include



from shelf.views import AuthorListView, AuthorDetailView, BookListView, BookDetailView


urlpatterns = [
    url(r'^authors/$',AuthorListView.as_view(),name='author_list'),
    url(r'^authors/(?P<pk>\d+)/$', AuthorDetailView.as_view(),name='author_detail'),
    url(r'^books/$',BookListView.as_view(),name='book_list'),
    url(r'^books/(?P<pk>\d+)/$', BookDetailView.as_view(),name='book_detail'),
    ]

Rental/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import  User
from shelf.models import BookItem
#from django.conf import settings
from django.utils.timezone import now

class Rental (models.Model):
  #  who = models.ForeignKey(settings.AUTH_USER_MODEL)

    who = models.ForeignKey(User)
    what = models.ForeignKey(BookItem)
    when = models.DateTimeField(default=now)
    returned = models.DateTimeField(null=True, blank=True)
    #To pole moze puste przy wysylaniu

    def __str__(self):
        return '' #zaddom

contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return "message from {name}".format(name=self.name)

shelf/models.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import
from django.core.urlresolvers import reverse_lazy
###############################

from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return "{first_name} {last_name}".format(first_name=self.first_name,
                                                 last_name=self.last_name)




class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name



class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book (models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)
    #author = models.ForeignKey('Author')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('shelf:book_detail', kwargs={'pk':self.id})


class BookEdition (models.Model):
    """
    Wydanie określonej książki
    """
    book = models.ForeignKey(Book,related_name='editions')
    isbn = models.CharField(max_length=17, blank='true')
    date = models.DateField()
    publisher = models.ForeignKey('Publisher')

    def __str__(self):
       return "{book.title}, {publisher.name}".format(book=self.book, publisher=self.publisher)

COVER_TYPES = (
    ('soft','Soft'),
    ('hard','Hard')
    #(wartosc w bazie, wartosc wyswietlana)
)


class BookItem(models.Model):
    """
    Konkretny egzemplarz
    """
    edition = models.ForeignKey(BookEdition)
    catalogue_number = models.CharField(max_length=30)
    cover_type = models.CharField(max_length=4,choices=COVER_TYPES)

    def __str__(self):
        return "{edition},{cover}".format(edition=self.edition,
                                          cover=self.get_cover_type_display())

users/models.py
from __future__ import unicode_literals
from django.db import models
# from django.contrib.auth.models import AbstractUser
#
#
# class BiblioUser(AbstractUser):
#     avatar = models.ImageField(upload_to='avatars/')
#     phone = models.CharField(max_length=15)

contact/forms.py
from __future__ import unicode_literals
from .models import Message
from django import  forms



class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name','email','message')



class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

Rental/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render
from django.views.generic import DetailView, FormView
from .models import Message
from .forms import MessageForm, ContactForm

#class MessageDetailView(DetailView):
#    model = Message

class MessageAddView(FormView):
    form_class = ContactForm
    template_name = 'contact/message_detail.html'
    success_url = '/'

 #   def form_valid(self, form):
 #       form.save()
 #       return super (MessageAddView, self).form_valid(self)
    ## GDY FORMULARZ JEST POPRAWNY TO WYKONUJE ISE TA METODA

shelf/views.py
#coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.views.generic import ListView, DetailView, TemplateView
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from .models import Author, Book

class MainPageView(TemplateView):
    template_name = 'index.html'

index_view = MainPageView.as_view()

# def index_view(request, *args, **kwargs):
#     return HttpResponse('OK - funkcja')




class AuthorListView(ListView):
    model = Author


class AuthorDetailView(DetailView):

    model = Author

class BookListView(ListView):
    model = Book

class BookDetailView(DetailView):
    model = Book

users/views.py
from django.shortcuts import render

# Create your views here.

contact/templates/contact/message_detail.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Wyślij</button>
    </form>
{%  endblock %}

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block content %}

<div><a href="{% url 'shelf:author_list'%}"> Powrot do listy autorów</a></div>
Profil Autora {{ object.last_name }}, {{ object.first_name }}

<h2>Ksiazki:</h2>
<ul>
{% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">
{#    <li><a href="{% url 'shelf:book_detail' book.id %}">#}
        {{ book.title }}
    </li>
{% endfor %}

</ul>

{#<div><a href="{% url 'author_list'%}"> Powrot do listy </a></div>#}
{#{{ object }}#}

{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for author in object_list %}

    <li> <a href="{% url 'shelf:author_detail' author.id %}"> {{ author.first_name }} {{ author.last_name }}</li>


{% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}{% load shelf_tags %}

{% block content %}


<div><a href="{% url 'shelf:author_list'%}"> Powrot do listy autorów</a></div>
<div><a href="{% url 'shelf:book_list'%}"> Powrot do listy książek</a></div>
    {{ object.title }}

    <h2>Wydania:</h2>

    {% show_editions object %}

{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for book in object_list %}
    <li><a href="{% url 'shelf:book_detail' book.id %}">
        {{ book.title }} - {% for author in book.authors.all %}
        {{ author.first_name }} {{ author.last_name }}
        {% if not forloop.last %}
        {% endif %}
        {% endfor %}
    </li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/tags/show_editions.html
{% load shelf_tags %}

{% for edition in editions %}
<li>{{ edition.date|pub_date }} - {{ edition.publisher.name }}</li>
{% endfor %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "http://www.w3.org/TR/xhtml1/xhtml1-strict.dtd">
<HTML xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <HEAD>
    <TITLE>bez nazwy</TITLE>
    <META http-equiv="Content-Type" content="text/html; charset=utf=8" />
      <meta name="generator" content="Geany 1.24.1" />
  </HEAD>
<BODY>
<!---tresc naszej strony tutaj -->

    <div>
        MENU GŁÓWNE:
        {% if user.is_authenticated %}
        <a href="{% url 'account_logout'%}">Wyloguj sie</a>
        {% else %}
        <a href="{% url 'account_login'%}">Zaloguj</a>,
        <a href="{% url 'account_signup'%}">Zaloz konto</a>

        {% load socialaccount %}
        {% providers_media_js %}
        <a href="{% provider_login_url 'facebook' method='js_sdk' %}">Facebook Connect</a>

        {% load socialaccount %}
        <a href="{% provider_login_url 'facebook' method='oauth2' %}">Facebook OAuth2</a>

        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</BODY>
</HTML>

templates/index.html
{%extends 'base.html' %}

{% block content%}

Strona główna

{%endblock %}

{% block title %} Strona główna {%endblock %}